-- Таблица и view FR-валидации на Greenplum создаются и наполняются ETL.
-- Приложение только читает/пишет в t_db_oarb_ck_fr_validation.
--
-- Связанная таблица t_db_oarb_ck_validation_reestr_metric (реестр метрик)
-- также управляется ETL. Содержит присвоенные ID метрик (формат ФР00001).
-- Связь: t_db_oarb_ck_fr_validation.reestr_metric_id → id этой таблицы.
